name: Deploy
on:
  push:
    branches:
      - master

jobs:
 build:
  name: Run web app
  runs-on: ubuntu-latest
  steps:
    - name: Build web App
      run: |
       echo "Build web App"
       sleep 10s
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with: 
        owner: sushantAtwork
        repo: front_end_trigger
        github_token: ${{ secrets.TEST_REPO }}
        workflow_file_name: master.yml
        ref: master
    - name : Deploy web app
      run: |
        echo "Deploy web App"
        sleep 10s
    
    
