name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run web app
    runs-on: ubuntu-latest
    steps:
      - name: Build web App
        run: |
          echo "Build web App"
          sleep 10s

      # - uses: convictional/trigger-workflow-and-wait@v1.6.5
      - uses: peter-evans/repository-dispatch@v2
        with:
          owner: sushantAtwork
          repo: back_end_trigger
          github_token: ${{ secrets.TEST_REPO }}
          workflow_file_name: master.yml
          propagate_failure: false
          # trigger_workflow: true
          ref: main

      - name: Deploy web app
        run: |
          echo "Deploy web App"
          sleep 10s
