name: Deploy
on: workflow_dispatch
jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps: 
      - name: trigger the repository
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_REPO }}
          repository : sushantAtwork/back_end_trigger
          event-type: my_event
          client-payload: '{ "github": ${{ toJson(github) }}}'
          
